version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8080